# Generated by Django 3.2.10 on 2021-12-31 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='address',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='participant',
            name='company',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
