# Generated by Django 3.2.10 on 2021-12-12 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='deskripsi',
        ),
        migrations.RemoveField(
            model_name='event',
            name='event_website',
        ),
        migrations.RemoveField(
            model_name='event',
            name='flyer',
        ),
        migrations.RemoveField(
            model_name='event',
            name='hosted_by',
        ),
        migrations.RemoveField(
            model_name='event',
            name='organized_by',
        ),
        migrations.RemoveField(
            model_name='event',
            name='tempat',
        ),
    ]
