# Generated by Django 3.2.10 on 2021-12-12 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_auto_20211212_1424'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='tanggal',
        ),
    ]
