# Generated by Django 3.2.10 on 2021-12-27 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_auto_20211227_1926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='hosted_by',
            field=models.CharField(max_length=100),
        ),
    ]
