# Generated by Django 3.2.10 on 2022-01-03 12:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0003_auto_20220101_1406'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participanttype',
            name='event',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='event.event'),
        ),
    ]
