# Generated by Django 3.2.10 on 2021-12-28 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0003_alter_event_hosted_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_website',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='no_rek',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='topic',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
