# Generated by Django 3.2.10 on 2021-12-28 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0004_auto_20211228_1432'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='tanggal',
        ),
        migrations.AddField(
            model_name='event',
            name='end',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='start',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_website',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='no_rek',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
