# Generated by Django 3.2.10 on 2021-12-16 16:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_user_options'),
        ('event', '0005_auto_20211216_2315'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='hosted_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.user'),
        ),
    ]
