# Generated by Django 3.2.10 on 2021-12-28 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0005_auto_20211228_1518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='announcement',
            field=models.ImageField(blank=True, null=True, upload_to='static/image/logo_organization'),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_pict',
            field=models.ImageField(blank=True, null=True, upload_to='static/image/announcement'),
        ),
        migrations.AlterField(
            model_name='event',
            name='logo_organization',
            field=models.ImageField(blank=True, null=True, upload_to='static/image/event_pic'),
        ),
    ]
