# Generated by Django 3.2.10 on 2021-12-22 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0007_message'),
    ]

    operations = [
        migrations.RenameField(
            model_name='topic',
            old_name='nama',
            new_name='name',
        ),
    ]
