# Generated by Django 3.2.10 on 2021-12-23 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0008_rename_nama_topic_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='hosted_by',
            new_name='hosted',
        ),
    ]
