# Generated by Django 3.2.10 on 2021-12-12 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['-updated', '-created']},
        ),
    ]
